import type { Branding } from "./schema";

export const PRESETS: Record<string, Branding> = {
  corporate: {
    primaryColor: "#1a365d",
    secondaryColor: "#2b6cb0",
    accentColor: "#3182ce",
    backgroundColor: "#ffffff",
    textColor: "#1a202c",
    headingFont: "Inter",
    bodyFont: "Inter",
    fontSizeBase: 18,
    fontSizeLg: 28,
    fontSizeXl: 48,
    borderRadius: 4,
    spacing: 16,
  },
  modern: {
    primaryColor: "#8b5cf6",
    secondaryColor: "#6d28d9",
    accentColor: "#a78bfa",
    backgroundColor: "#111827",
    textColor: "#f9fafb",
    headingFont: "Space Grotesk",
    bodyFont: "Inter",
    fontSizeBase: 18,
    fontSizeLg: 28,
    fontSizeXl: 48,
    borderRadius: 8,
    spacing: 16,
  },
  minimal: {
    primaryColor: "#18181b",
    secondaryColor: "#71717a",
    accentColor: "#a1a1aa",
    backgroundColor: "#fafafa",
    textColor: "#18181b",
    headingFont: "Inter",
    bodyFont: "Inter",
    fontSizeBase: 16,
    fontSizeLg: 24,
    fontSizeXl: 40,
    borderRadius: 2,
    spacing: 16,
  },
  "redhat-light": {
    primaryColor: "#ee0000",
    secondaryColor: "#0066cc",
    accentColor: "#cc0000",
    backgroundColor: "#ffffff",
    textColor: "#151515",
    headingFont: "Red Hat Display",
    bodyFont: "Red Hat Text",
    fontSizeBase: 18,
    fontSizeLg: 28,
    fontSizeXl: 48,
    borderRadius: 0,
    spacing: 16,
  },
  "redhat-dark": {
    primaryColor: "#ee0000",
    secondaryColor: "#2b9af3",
    accentColor: "#cc0000",
    backgroundColor: "#151515",
    textColor: "#ffffff",
    headingFont: "Red Hat Display",
    bodyFont: "Red Hat Text",
    fontSizeBase: 18,
    fontSizeLg: 28,
    fontSizeXl: 48,
    borderRadius: 0,
    spacing: 16,
  },
};
